name: pre_merge

on: pull_request

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - uses: pre-commit/action@v3.0.0

  run_tests:

    runs-on: ubuntu-latest
    env:
      DB_URI_ANALYTICS: postgresql://postgres:postgres@localhost:5432/postgres

    services:
      postgres:
        image: bitnami/postgresql:14.2.0-debian-10-r4
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: mobilidade

    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        name: clone this repo

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: install requirements
        run: pip install -r requirements/requirements.txt

      - name: run migrations on docker service
        run: alembic upgrade head

      - name: run tests
        run: pytest --cov-report term --cov=db-mobilidade/
